swagger: '2.0'
info:
  title: CueServer REST API
  description: For accessing common CueServer functions with REST
  version: 1.1.0
host: cueserver-rest.herokuapp.com
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /system:
    get:
      summary: System Info
      description: |
        The System endpoint gets the current system information from the CueServer
      tags:
        - System
      responses:
        '200':
          description: System information
          schema:
              $ref: '#/definitions/System'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /playback:
    get:
      tags:
        - Playback
      summary: Plackback Info
      description: |
        Get the summary of a CueServer's playbacks
      tags:
        - Playback
      parameters:
        - name: playback
          in: query
          description: The number of thr playback to get
          type: integer
          required: false
          default: 1
          minimum: 1
          maximum: 4
      responses:
        '200':
          description: Playback information
          schema:
              $ref: '#/definitions/Playback'
        '400':
          description: Playback data was not valid
    post:
      tags:
        - Playback
      description: |
        Plays a cue in the given playback
      operationId: playCue
      parameters:
        - name: cue
          in: body
          description: Cue and playback to be played
          required: true
          schema:
            $ref: '#/definitions/PlaybackCue'
      responses:
        '202':
          description: Cue played
        '400':
          description: Cue and/or playback data was not valid
definitions:
  System:
    type: object
    properties:
      deviceName:
        type: string
        description: The name of the CueServer.
      model:
        type: string
        description: The model of the CueServer.
      serialNumber:
        type: string
        description: The serial number.
      time:
        type: string
        description: The current time off of the CueServer.
      hasPassword:
        type: boolean
        description: True if the CueServer has a password, false if not.
  Playback:
    type: object
    properties:
      playback:
        type: string
        description: The ID of the playback.
      currentCue:
        $ref: '#/definitions/Cue'
        description: The current cue.
      nextCue:
        $ref: '#/definitions/Cue'
        description: The next cue inlined to be played.
  Cue:
    type: object
    properties:
      number:
        type: number
        description: The cue number.
      name:
        type: string
        description: The name of the cue.
  PlaybackCue:
    type: object
    properties:
      cueNumber:
        type: number
        description: The number of the cue to play.
      playbackNumber:
        type: integer
        description: The playback to the cue will be played on.
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string