swagger: '2.0'
info:
  title: CueServer REST API
  description: For accessing common CueServer functions with REST
  version: 1.0.0
host: cueserver-rest.herokuapp.com
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /system:
    get:
      summary: System Info
      description: |
        The System endpoint get the current system information from the CueServer
      tags:
        - System
      responses:
        '200':
          description: System information
          schema:
              $ref: '#/definitions/System'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  System:
    type: object
    properties:
      deviceName:
        type: string
        description: The name of the CueServer.
      model:
        type: string
        description: The model of the CueServer.
      serialNumber:
        type: string
        description: The serial number.
      time:
        type: string
        description: The current time off of the CueServer.
      hasPassword:
        type: boolean
        description: 'True if the CueServer has a password, false if not.'
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
