swagger: '2.0'
info:
  title: CueServer REST API
  description: For accessing common CueServer functions with REST
  version: 1.1.0
host: cueserver-rest.herokuapp.com
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /system:
    get:
      summary: System Info
      description: |
        The System endpoint gets the current system information from the CueServer
      tags:
        - System
      responses:
        '200':
          description: System information
          schema:
              $ref: '#/definitions/System'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /playback/{number}:
    get:
      tags:
        - Playback
      summary: Plackback Info
      operationId: getPlayback
      description: |
        Get the summary of a CueServer's playback.
      tags:
        - Playback
      parameters:
        - name: number
          in: path
          description: The number of the playback to get the status of.
          required: true
          type: integer
          format: int32
          minimum: 1
          maximum: 4
      responses:
        '200':
          description: Playback information
          schema:
              $ref: '#/definitions/Playback'
        '400':
          description: Playback data was not valid
  '/playback/{number}/cue/{cueNumber}':
    put:
      tags:
        - Playback
      description: |
        Plays a cue in the given playback
      operationId: playCue
      parameters:
        - name: number
          in: path
          description: The number of the playback to get the status of.
          required: true
          type: integer
          format: int32
          minimum: 1
          maximum: 4
        - name: cueNumber
          in: path
          description: The number of the cue to play on the playback
          required: true
          type: number
          format: double
          minimum: 1.0
      responses:
        '202':
          description: Cue played
        '400':
          description: Cue and/or playback data was not valid
  '/playback/clear/{number}':
    put:
      tags:
        - Playback
      description: |
        Plays a cue in the given playback
      operationId: clearPlayback
      parameters:
        - name: number
          in: path
          description: The number of the playback to get the status of.
          required: true
          type: integer
          format: int32
          minimum: 1
          maximum: 4
      responses:
        '202':
          description: Playback cleared
        '400':
          description: Playback data was not valid
  /cue:
    put:
      tags:
        - Cue
      description: |
        Records the current levels to the given cue
      parameters:
        - name: cue
          in: body
          description: Cue to be recorded
          required: true
          schema:
            $ref: '#/definitions/RecordedCue'
      responses:
        '201':
          description: Cue recorded
        '400':
          description: Cue data was not valid
  '/cue/{cueNumber}':
    delete:
      tags:
        - Cue
      description: Deletes the given cue
      operationId: deleteCue
      parameters:
        - name: cueNumber
          in: path
          description: deletes the given cue
          required: true
          type: number
          format: double
      responses:
        200:
          description: OK
  /channel:
    get:
      tags:
        - Channel
      description: |
        Get the levels for the given range of channels.
      parameters:
        - name: start
          in: query
          description: the first channel
          required: false
          type: integer
          format: int32
          default: 1
          minimum: 1
          maximum: 512
        - name: end
          in: query
          description: the last channel
          required: false
          type: integer
          format: int32
          default: 512
          minimum: 1
          maximum: 512
      responses:
        '200':
          description: Request valid
        '400':
          description: Channels were not valid
  '/channel/{channelNumber}/{level}':
    put:
      tags:
        - Channel
      description: |
        Sets the given channel to a level
      operationId: setChannel
      parameters:
        - name: channelNumber
          in: path
          required: true
          description: The channel to set
          type: integer
          format: int32
          minimum: 1
          maximum: 512
        - name: level
          in: path
          required: true
          description: The channel to set
          type: integer
          format: int32
          minimum: 0
          maximum: 255
      responses:
        '200':
          description: Request valid
        '400':
          description: Channels were not valid
definitions:
  System:
    type: object
    properties:
      deviceName:
        type: string
        description: The name of the CueServer.
      model:
        type: string
        description: The model of the CueServer.
      serialNumber:
        type: string
        description: The serial number.
      time:
        type: string
        description: The current time off of the CueServer.
      hasPassword:
        type: boolean
        description: True if the CueServer has a password, false if not.
  Playback:
    type: object
    properties:
      playback:
        type: string
        description: The ID of the playback.
      currentCue:
        $ref: '#/definitions/Cue'
        description: The current cue.
      nextCue:
        $ref: '#/definitions/Cue'
        description: The next cue inlined to be played.
  Cue:
    type: object
    properties:
      number:
        type: number
        description: The cue number.
      name:
        type: string
        description: The name of the cue.
  RecordedCue:
    type: object
    properties:
      number:
        type: number
        description: the cue's numbers
      uptime:
        type: number
        description: the cue's uptime
      downtime:
        type: number
        description: the cue's downtime
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string